### ISSUE TITLE
Getting error when  trying to use Azure/network/azurerm

### ISSUE THREAD

**Issue by asote** [Azure/terraform-azurerm-network#10]
Initializing modules...
- module.network
  Found version 1.0.0 of Azure/network/azurerm on registry.terraform.io
  Getting source "Azure/network/azurerm"
Error downloading modules: Error loading modules: chmod .terraform/modules/d67a94276de399cc072a6a2c087a27cb/Azure-terraform-azurerm-network-6fc4665/.DS_Store: operation not permitted

**Comment by dcaro** [comment]
@asote I just tried the example in the README and ran terraform init with no issues. Can you share more details about when you get this error?
Can you try to run the example as well to rule out any transient issue?

**Comment by asote** [comment]
I used the example below.

module "network" {
  source  = "Azure/network/azurerm"
  version = "1.0.0"

  # insert the 1 required variable here


Received the same error when running terraform init.

antonio@Azure:~/clouddrive/test$ terraform init
Initializing modules...
- module.network
  Found version 1.0.0 of Azure/network/azurerm on registry.terraform.io
  Getting source "Azure/network/azurerm"
Error downloading modules: Error loading modules: chmod .terraform/modules/d67a94276de399cc072a6a2c087a27cb/Azure-terraform-azurerm-network-6fc4665/.DS_Store: operation not permitted


Sent from Mail for Windows 10

**Comment by asote** [comment]
Tested this again. I works fine from my workstation but it doesn’t from Azure Cloud Shell. I believe the problem is with permissions in Azure Cloud Shell.

Sent from Mail for Windows 10

From: Antonio Sotelo
Sent: Saturday, December 23, 2017 1:06 PM
To: Azure/terraform-azurerm-network
Subject: RE: [Azure/terraform-azurerm-network] Getting error when trying touseAzure/network/azurerm (#10)

I used the example below.

module "network" {
  source  = "Azure/network/azurerm"
  version = "1.0.0"

  # insert the 1 required variable here


Received the same error when running terraform init.

antonio@Azure:~/clouddrive/test$ terraform init
Initializing modules...
- module.network
  Found version 1.0.0 of Azure/network/azurerm on registry.terraform.io
  Getting source "Azure/network/azurerm"
Error downloading modules: Error loading modules: chmod .terraform/modules/d67a94276de399cc072a6a2c087a27cb/Azure-terraform-azurerm-network-6fc4665/.DS_Store: operation not permitted


Sent from Mail for Windows 10

**Comment by dcaro** [comment]
@asote, can you confirm the following:
- Is your code located in the ~/clouddrive folder in your cloudshell or are you running it somewhere else ?
- If you run the init command twice, do you have the same error the second time?

**Comment by asote** [comment]
Running terraform init from ~/clouddrive folder fails to download all the files with an operation not permitted error message not matter how many times the init command is ran.

Running terraform init from my desktop machine works fine.

**Comment by dcaro** [comment]
Thanks, do you mind sharing the region that you are using? (you can send by mail if you want).

**Comment by asote** [comment]
centralus

**Comment by dcaro** [comment]
Related issue: https://github.com/hashicorp/terraform/issues/17115

**Comment by dcaro** [comment]
@asote we have found and fixed the issue in Cloudshell. It will be rolled out as part of our regular update mechanism. I'm closing this issue as we have fixed it. Let me known if you have any questions.

**Comment by asote** [comment]
I tested it today and it's still broken.  When will it be rolled out?

**Comment by dcaro** [comment]
It has been deployed last week-end. Since the issue was in the way we mounted the clouddrive, you will have to unmount your clouddrive and remount it.

**Comment by asote** [comment]
@dcaro Deleted and recreated my cloud shell storage and still having the same issue.

antonio@Azure:~/clouddrive/terraformfiles$ terraform init
Initializing modules...
- module.loadbalancer
  Found version 1.0.1 of Azure/loadbalancer/azurerm on registry.terraform.io
  Getting source "Azure/loadbalancer/azurerm"
- module.windowsservers
  Found version 1.1.5 of Azure/compute/azurerm on registry.terraform.io
 
 Getting source "Azure/compute/azurerm"
- module.windowsservers.os
  Getting source "./os"
Error downloading modules: Error loading modules: error downloading 'file:///home/antonio/clouddrive/terraformfiles/.terraform/modules/a9981d0889be4b075884bd6029477886/Azure-terraform-azurerm-compute-fbe03a6/os': symlink /home/antonio/clouddrive/terraformfiles/.terraform/modules/a9981d0889be4b075884bd6029477886/Azure-terraform-azurerm-compute-fbe03a6/os .terraform/modules/e05e52039b3b6fa1a361c8b954701273: operation not supported
antonio@Azure:~/clouddrive/terraformfiles$
